title: Zongwei Wang's Homepage
page-top-title: Hi, I'm Zongwei
top-section-bg-text: Zongwei Wang
home-subtitle: Zongwei Wang&ensp;|&ensp;王宗威
copyright-text: '&copy; Zongwei Wang 2024-2025. All Rights Reserved.'
